---
swagger: "2.0"
info:
  description: "TBW"
  version: "1.0.0"
  title: "Auto Remedy Scheduler"
  contact:
    email: "martin@englund.nu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /schedule:
    post:
      summary: "Schedule a new job"
      description: ""
      operationId: "createJob"
      tags:
        - schedule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Job object that will be scheduled"
          required: true
          schema:
            $ref: "#/definitions/Job"
      responses:
        405:
          description: "Invalid input"
    get:
      summary: "List scheduled jobs"
      description: ""
      operationId: "listJobs"
      tags:
        - schedule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters: []
      responses:
        405:
          description: "Invalid input"
  /schedule/{id}:
    delete:
      summary: "Delete a scheduled job"
      description: ""
      operationId: "deleteJob"
      tags:
        - schedule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of job that needs to be deleted"
          required: true
          type: "integer"
          minimum: 1.0
          format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Schedule not found"
definitions:
  Job:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      at:
        type: "string"
        format: "date-time"
      in:
        type: "string"
        pattern: '^\d+[smh]$'
      status:
        type: "string"
        description: "Job Status"
        enum:
          - "pending"
          - "running"
          - "complete"
        default: "pending"
